import {createRequire} from 'node:module';import os from 'node:os';import path from 'node:path';import {mkdir,writeFile,readFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const origin='http://127.0.0.1:3030',output=path.resolve('workbench/final');await mkdir(output,{recursive:true});
const resume=process.argv.includes('--resume'),prior=resume?JSON.parse(await readFile(path.join(output,'production-report.json'),'utf8')):{};let newestId=prior.newestId;
const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1440,height:900},...(resume?{storageState:path.join(output,'browser-session.json')}:{})});
const errors=[],httpFailures=[],requests=prior.requests??[],jobs=prior.jobs??[],metrics=prior.metrics??[];page.on('pageerror',e=>errors.push(e.message));page.on('response',async r=>{if(r.status()>=400)httpFailures.push({url:r.url(),status:r.status()});if(new URL(r.url()).pathname.startsWith('/api/jobs/')&&r.ok()){const d=await r.json().catch(()=>null);if(d?.job)jobs.push({id:d.job.id,status:d.job.status});}});page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/jobs')requests.push(r.postDataJSON());});
const shot=name=>page.screenshot({path:path.join(output,name+'.png'),animations:'disabled'});
const edit=async(name,value)=>{const input=page.getByRole('spinbutton',{name,exact:true});await input.fill(String(value));await input.press('Tab');};
const close=()=>page.locator('dialog[open]').last().getByRole('button',{name:/^(閉じる|Canvasへ戻る)$/}).click();
const phase=value=>page.waitForFunction(value=>document.querySelector('.canvas-stage').dataset.state===value,value,{timeout:300000});
const imageReady=()=>page.waitForFunction(()=>{const i=document.querySelector('.artwork');return i?.complete&&i.naturalWidth>0;});
const overflow=()=>page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
const dims=()=>page.evaluate(()=>({canvas:document.querySelector('.canvas-stage').getBoundingClientRect().height,dock:document.querySelector('.prompt-dock').getBoundingClientRect().height}));
try {
 if(!resume){
 const before=(await (await page.request.get(origin+'/api/jobs')).json()).jobs??[];assert.equal(before.filter(j=>['queued','running'].includes(j.status)).length,0);
 const start=performance.now();await page.goto(origin+'/');await page.waitForFunction(()=>!document.querySelector('.prompt-open').disabled);metrics.push({operation:'Production ready',ms:Math.round(performance.now()-start)});
 assert.equal(await page.locator('.preview-badge').textContent(),'LOCAL');assert.equal(await page.locator('script[src="/app.js"]').count(),0);
 await page.getByRole('button',{name:'Structured · 編集',exact:true}).click();
 for(const [name,value]of Object.entries({'キャラクター':'a small ceramic teapot and a single orange','容姿・衣装':'ivory glaze, matte texture','ポーズ・構図':'still life, balanced composition','シチュエーション・背景':'wooden table by a window, afternoon light','画風・品質':'warm illustration, detailed','追加プロンプト':'quiet atmosphere'}))await page.getByRole('textbox',{name,exact:true}).fill(value);
 await page.getByRole('textbox',{name:'Negative Prompt',exact:true}).fill('text, watermark, blur');const final=await page.getByRole('textbox',{name:'Final Positive Prompt',exact:true}).inputValue();await shot('prompt-1440');await close();
 await page.locator('.resolution-summary').click();await page.getByText('Custom dimensions',{exact:true}).click();await edit('Width',768);await edit('Height',768);await edit('Seed',515101);await close();
 if(page.viewportSize().width<=900) await page.getByRole('button',{name:'制作設定',exact:true}).click();await edit('Steps',16);await page.keyboard.press("Escape");
 const loraStart=performance.now();await page.getByRole('button',{name:'Active LoRA',exact:true}).click();await page.locator('.lora-asset').first().waitFor();metrics.push({operation:'LoRA catalog',ms:Math.round(performance.now()-loraStart)});
 await page.getByRole('searchbox',{name:'Search LoRA'}).fill('anima-base-1-flat-color-v3');await page.locator('.lora-asset').first().click();await page.getByRole('button',{name:'Add to Composition',exact:true}).click();await edit('Selected LoRA weight',.55);await shot('lora-detail-1440');await page.getByRole('button',{name:'Close LoRA Browser'}).click();
 await shot('before-1440');const generationStart=performance.now();await page.getByRole('button',{name:'Generate',exact:true}).click();await page.waitForFunction(()=>['queued','generating'].includes(document.querySelector('.canvas-stage').dataset.state));
 assert.equal(requests[0].prompt,final);assert.equal(requests[0].negativePrompt,'text, watermark, blur');assert.equal(requests[0].loras[0].name,'anima-base-1-flat-color-v3');assert.equal(requests[0].loras[0].weight,.55);await shot('generating-1440');
 await page.reload();await phase('completed');assert.equal(requests.length,1,'reload must not resubmit');await imageReady();metrics.push({operation:'Real generate with reload reattach',ms:Math.round(performance.now()-generationStart)});await shot('completed-1440');console.log('Production real Structured + LoRA + reload reattach + Canvas PASS');
 await page.getByRole('button',{name:'Library',exact:true}).click();await page.locator('.image-library-grid .library-image').first().waitFor();newestId=await page.locator('.image-library-grid .library-image').first().getAttribute('aria-label');
 await page.getByRole('searchbox',{name:'Search all history'}).fill('ceramic teapot');await page.waitForResponse(r=>r.url().includes('/api/history?')&&r.url().includes('search=ceramic'));await page.getByRole('combobox',{name:'History sort',exact:true}).selectOption('oldest');await page.waitForResponse(r=>r.url().includes('/api/history?')&&r.url().includes('sort=oldest'));
 await page.locator('.image-library-grid .library-image').first().click();await page.locator('.viewer-image').evaluate(i=>i.decode());await shot('historical-viewer-1440');assert.ok((await page.locator('.library-viewer .viewer-metadata').textContent()).includes('prompt'));
 await page.getByRole('button',{name:'Studioで再利用',exact:true}).click();await page.getByRole('dialog',{name:'Image Viewer'}).waitFor({state:'hidden'});assert.equal(await page.locator('.studio-shell').getAttribute('data-view'),'studio');
 await page.locator('.seed-summary').click();await edit('Seed',515102);await close();await page.getByRole('button',{name:'Generate',exact:true}).click();await phase('completed');await imageReady();assert.equal(requests[1].settings.seed,515102);console.log('Production full History search / oldest / metadata / explicit reuse / second generate PASS');
 await page.getByRole('button',{name:'Generate',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).waitFor();await page.getByRole('button',{name:'Cancel',exact:true}).click();await phase('cancelled');assert.equal(requests.length,3);await shot('cancelled-1440');console.log('Production Cancel PASS');
 } else { await page.goto(origin+'/');await page.waitForFunction(()=>!document.querySelector('.prompt-open').disabled); }
 await page.getByRole('button',{name:'Studio',exact:true}).click();await page.locator('.prompt-open').click();await page.getByRole('button',{name:'Structured',exact:true}).click();
 for(const [name,value]of Object.entries({'キャラクター':'a small ceramic teapot and a single orange','容姿・衣装':'ivory glaze, matte texture','ポーズ・構図':'still life, balanced composition','シチュエーション・背景':'wooden table by a window, afternoon light','画風・品質':'warm illustration, detailed','追加プロンプト':'quiet atmosphere'})){const input=page.getByRole('textbox',{name,exact:true});if(!await input.inputValue())await input.fill(value);}
 await close();
 // Keep the completed result selected; mobile navigations and inspection must not mutate its draft.
 for(const [width,height,canvas,dock]of [[1280,900,624,178],[1440,900,624,178],[1920,1080,782,196],[390,844,496,202],[430,932,584,202]]){
  await page.setViewportSize({width,height});await page.getByRole('button',{name:'Studio',exact:true}).click();await imageReady();assert.equal(await overflow(),false);assert.deepEqual(await dims(),{canvas,dock});await shot('studio-'+width);metrics.push({width,height,...await dims()});
  await page.locator('.prompt-open').click();await page.getByRole('button',{name:'Structured',exact:true}).click();await shot('prompt-'+width);if(width<500){await page.getByRole('button',{name:'Raw',exact:true}).click();await page.setViewportSize({width,height:440});await page.getByRole('textbox',{name:'Raw Prompt',exact:true}).scrollIntoViewIfNeeded();assert.equal(await page.locator('.prompt-workspace').evaluate(n=>n.scrollWidth<=n.clientWidth),true);await page.setViewportSize({width,height});await page.getByRole('button',{name:'Structured',exact:true}).click();}await close();
  if(page.viewportSize().width<=900) await page.getByRole('button',{name:'制作設定',exact:true}).click();await shot('inspector-'+width);await page.keyboard.press("Escape");
  await page.locator('.model-summary').click();await page.getByRole('searchbox',{name:'Model search'}).fill('Anima');assert.equal(await overflow(),false);await shot('models-'+width);await close();
  await page.getByRole('button',{name:'Active LoRA',exact:true}).click();await page.getByRole('searchbox',{name:'Search LoRA'}).fill('Anima/Style');await page.locator('.lora-asset').first().waitFor();if(width<1001){await page.getByRole('button',{name:'Folders',exact:true}).click();await page.getByRole('navigation',{name:'LoRA folders',exact:true}).getByRole('button',{name:'All LoRA',exact:true}).click();}assert.equal(await page.getByLabel('Current LoRA folder',{exact:true}).getByRole('button').count(),0);await shot('lora-'+width);await page.getByRole('button',{name:'Close LoRA Browser'}).click();
  await page.getByRole('button',{name:'Library',exact:true}).click();await page.locator('.image-library-grid .library-image').first().waitFor();assert.equal(await overflow(),false);await shot('library-'+width);await page.locator('.image-library-grid .library-image').first().click();await page.locator('.viewer-image').evaluate(i=>i.decode());assert.equal(await page.locator('.viewer-image-area').evaluate(n=>n.scrollHeight<=n.clientHeight&&n.scrollWidth<=n.clientWidth),true,'Fit must display the whole image');await shot('viewer-'+width);assert.equal(await overflow(),false);await close();
 }
 await page.reload();await page.waitForFunction(()=>!document.querySelector('.prompt-open').disabled);assert.equal(await page.locator('.studio-shell').getAttribute('data-view'),'library');assert.equal(await page.getByRole('searchbox',{name:'Search all history'}).inputValue(),'ceramic teapot');assert.equal(requests.length,3);await page.getByRole('button',{name:'Studio',exact:true}).click();
 for(const url of ['/index.html','/studio-next/']){await page.goto(origin+url);await page.waitForFunction(()=>!document.querySelector('.prompt-open').disabled);assert.equal(await page.locator('.preview-badge').textContent(),'LOCAL');}
 await page.evaluate(async()=>{const r=await navigator.serviceWorker.ready;await r.update();});assert.deepEqual(await page.evaluate(()=>caches.keys()),[]);
 const legacy=await page.request.get(origin+'/?legacy=1');assert.ok((await legacy.text()).includes('id="mainNav"'));
 assert.equal(await page.evaluate(()=>[...document.images].filter(i=>i.currentSrc&&i.complete&&!i.naturalWidth).length),0);assert.deepEqual(errors,[]);assert.deepEqual(httpFailures,[]);
 await page.context().storageState({path:path.join(output,'browser-session.json')});
 await writeFile(path.join(output,'production-report.json'),JSON.stringify({result:'PASS',origin,requests,jobs,metrics,newestId,errors,httpFailures,checks:['real Structured/LoRA Generate','reload reattach without POST','Library search/oldest','metadata/reuse/regenerate','Cancel','five viewport Production surfaces','no overflow','SW network only','direct navigation','legacy fallback','session and Library restore']},null,2));console.log('Production browser and real provider PASS');
} catch(error){await page.context().storageState({path:path.join(output,'browser-session.json')});await shot('failure');await writeFile(path.join(output,'production-report.json'),JSON.stringify({result:'FAIL',error:error.message,requests,jobs,metrics,errors,httpFailures},null,2));throw error;} finally {await browser.close();}
